name: "Migração de repos do Azure DevOps para GitHub"

env:
  GH_PAT: ${{ secrets.TARGET_TOKEN }}
  ADO_PAT: ${{ secrets.SOURCE_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      ado_org:
        description: "Organização do Azure DevOps"
        required: true
        default: ""
        type: string
      target_org:
        description: "Organização de destino no GitHub"
        required: true
        default: ""
        type: string
      ado_team_project:
        description: "Projeto contendo os repos a serem migrados"
        required: true
        default: "nome_do_projeto"
        type: string
      ado_repo_list:
        description: "Lista de repos do Azure DevOps (separados por vírgula)"
        required: true
        default: "repo1,repo2,repo3"
        type: string
      archive_ado_repos:
        description: "Arquivar os repositórios no Azure DevOps após migração (default: true)"
        required: false
        default: true
        type: boolean
      reviewer_team:
        description: "Time do GitHub para adicionar como revisor nos PRs (ex: team_approvers)"
        required: true
        type: string
      topic_tag:
        description: "Tag de tópico para adicionar nos repositórios migrados (ex: 'migrado-ado')"
        required: true
        type: string

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-repos: ${{ steps.set-matrix.outputs.repos }}
    steps:
      - name: "Configurar matriz de Repos"
        id: set-matrix
        run: |
          repos_json=$(echo "${{ github.event.inputs.ado_repo_list }}" | tr -d ' ' | tr ',' '\n' | jq -R . | jq -s -c .)
          echo "repos=$repos_json" >> $GITHUB_OUTPUT
  
  migrate-repos:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: ${{ fromJson(needs.setup-matrix.outputs.matrix-repos) }}
      fail-fast: false

    steps:
      - name: "Migrar repositório ${{ matrix.repos }}"
        uses: /.github/actions/migrate-repo
        with:
          repo: ${{ matrix.repos }}
          gh_pat: ${{ env.GH_PAT }}
          ado_pat: ${{ env.ADO_PAT }}
          gh_org: ${{ github.event.inputs.target_org }}
          ado_org: ${{ github.event.inputs.ado_org }}
          ado_team_project: ${{ github.event.inputs.ado_team_project }}
          archive_ado_repos: ${{ github.event.inputs.archive_ado_repos }}

  configure-metadata:
    needs: [setup-matrix, migrate-repos]
    runs-on: ubuntu-latest
    if: success()
    strategy:
      matrix:
        repos: ${{ fromJson(needs.setup-matrix.outputs.matrix-repos) }}
    steps:
      - name: "Configurar metadados para o repositório ${{ matrix.repos }}"
        uses: /.github/actions/configure-metadata
        with:
          repo: ${{ matrix.repos }}
          gh_pat: ${{ env.GH_PAT }}
          gh_org: ${{ github.event.inputs.target_org }}
          ado_org: ${{ github.event.inputs.ado_org }}
          ado_team_project: ${{ github.event.inputs.ado_team_project }}
          topic_tag: ${{ github.event.inputs.topic_tag }}
          reviewer_team: ${{ github.event.inputs.reviewer_team }}

      - name: "Relatório de migração"
        if: always()
        run: echo "${{ matrix.repos }},${{ job.status }}" > status.txt

      - name: "Publicar relatório"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "status-${{ matrix.repos }}"
          path: status.txt

  report-migration:
    needs: [configure-metadata]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: "Baixar relatórios de migração"
        uses: actions/download-artifact@v4
        with:
          path: migration-statuses

      - name: Gerar relatório
        run: |
          echo "# Relatório de Migração ADO para GH" >> $GITHUB_STEP_SUMMARY
          find migration-statuses -name 'status.txt' -exec cat {} + | while IFS=, read -r repo status; do
            if [ "$status" == "success" ]; then
              echo "- ✅ $repo" >> $GITHUB_STEP_SUMMARY
            else
              echo "- ❌ $repo" >> $GITHUB_STEP_SUMMARY
            fi
          done
